name: student_booknote
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  objectbox: ^1.7.2
  objectbox_flutter_libs: ^1.7.2
  path_provider: ^2.0.13
  get_it: ^7.2.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  objectbox_generator: ^1.7.2
  build_runner: ^2.3.3

objectbox:
  output_dir: database

flutter:

  uses-material-design: true
